server:
  port: 8800
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
   password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 127.0.0.1
    #    username: root
    port: 6379
    timeout: 3000
    password: *****
  # 邮箱配置
  mail:
    host: smtp.qq.com
    # 用户名
    username: *******@qq.com
    # 授权码
    password: 邮箱授权码
    # 端口
    port: 587
  elasticsearch:
    rest:
      uris: ip:9200

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: 七牛云公钥
  secretKey: 七牛云私钥
  bucket: 储存库名称


file:
  upload-folder: /usr/local/upload/
  upload-url: 

#==============================IP限流次数和时间配置==============================
IpLimit:
  #请求次数
  count: 5
  #请求时间
  time: 10